// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUUDSPARTEXAMPLE_SUOS_UDS_MSG_TESTUNIVERSAL_H_
#define FLATBUFFERS_GENERATED_SUUDSPARTEXAMPLE_SUOS_UDS_MSG_TESTUNIVERSAL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace TestUniversal {

struct ScalarTable;
struct ScalarTableBuilder;

struct DataContainer;
struct DataContainerBuilder;

struct EmptySignal;
struct EmptySignalBuilder;

struct ConfigInfo;
struct ConfigInfoBuilder;

struct PayloadEnvelope;
struct PayloadEnvelopeBuilder;

enum UdsPayload : uint8_t {
  UdsPayload_NONE = 0,
  UdsPayload_ScalarTable = 1,
  UdsPayload_DataContainer = 2,
  UdsPayload_EmptySignal = 3,
  UdsPayload_ConfigInfo = 4,
  UdsPayload_MIN = UdsPayload_NONE,
  UdsPayload_MAX = UdsPayload_ConfigInfo
};

inline const UdsPayload (&EnumValuesUdsPayload())[5] {
  static const UdsPayload values[] = {
    UdsPayload_NONE,
    UdsPayload_ScalarTable,
    UdsPayload_DataContainer,
    UdsPayload_EmptySignal,
    UdsPayload_ConfigInfo
  };
  return values;
}

inline const char * const *EnumNamesUdsPayload() {
  static const char * const names[6] = {
    "NONE",
    "ScalarTable",
    "DataContainer",
    "EmptySignal",
    "ConfigInfo",
    nullptr
  };
  return names;
}

inline const char *EnumNameUdsPayload(UdsPayload e) {
  if (::flatbuffers::IsOutRange(e, UdsPayload_NONE, UdsPayload_ConfigInfo)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesUdsPayload()[index];
}

template<typename T> struct UdsPayloadTraits {
  static const UdsPayload enum_value = UdsPayload_NONE;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::TestUniversal::ScalarTable> {
  static const UdsPayload enum_value = UdsPayload_ScalarTable;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::TestUniversal::DataContainer> {
  static const UdsPayload enum_value = UdsPayload_DataContainer;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::TestUniversal::EmptySignal> {
  static const UdsPayload enum_value = UdsPayload_EmptySignal;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::TestUniversal::ConfigInfo> {
  static const UdsPayload enum_value = UdsPayload_ConfigInfo;
};

bool VerifyUdsPayload(::flatbuffers::Verifier &verifier, const void *obj, UdsPayload type);
bool VerifyUdsPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct ScalarTable FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ScalarTableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VAL_U8 = 4,
    VT_VAL_U32 = 6,
    VT_VAL_I64 = 8,
    VT_VAL_FLOAT = 10,
    VT_VAL_BOOL = 12
  };
  uint8_t val_u8() const {
    return GetField<uint8_t>(VT_VAL_U8, 0);
  }
  uint32_t val_u32() const {
    return GetField<uint32_t>(VT_VAL_U32, 0);
  }
  int64_t val_i64() const {
    return GetField<int64_t>(VT_VAL_I64, 0);
  }
  float val_float() const {
    return GetField<float>(VT_VAL_FLOAT, 0.0f);
  }
  bool val_bool() const {
    return GetField<uint8_t>(VT_VAL_BOOL, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VAL_U8, 1) &&
           VerifyField<uint32_t>(verifier, VT_VAL_U32, 4) &&
           VerifyField<int64_t>(verifier, VT_VAL_I64, 8) &&
           VerifyField<float>(verifier, VT_VAL_FLOAT, 4) &&
           VerifyField<uint8_t>(verifier, VT_VAL_BOOL, 1) &&
           verifier.EndTable();
  }
};

struct ScalarTableBuilder {
  typedef ScalarTable Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_val_u8(uint8_t val_u8) {
    fbb_.AddElement<uint8_t>(ScalarTable::VT_VAL_U8, val_u8, 0);
  }
  void add_val_u32(uint32_t val_u32) {
    fbb_.AddElement<uint32_t>(ScalarTable::VT_VAL_U32, val_u32, 0);
  }
  void add_val_i64(int64_t val_i64) {
    fbb_.AddElement<int64_t>(ScalarTable::VT_VAL_I64, val_i64, 0);
  }
  void add_val_float(float val_float) {
    fbb_.AddElement<float>(ScalarTable::VT_VAL_FLOAT, val_float, 0.0f);
  }
  void add_val_bool(bool val_bool) {
    fbb_.AddElement<uint8_t>(ScalarTable::VT_VAL_BOOL, static_cast<uint8_t>(val_bool), 0);
  }
  explicit ScalarTableBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ScalarTable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ScalarTable>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ScalarTable> CreateScalarTable(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t val_u8 = 0,
    uint32_t val_u32 = 0,
    int64_t val_i64 = 0,
    float val_float = 0.0f,
    bool val_bool = false) {
  ScalarTableBuilder builder_(_fbb);
  builder_.add_val_i64(val_i64);
  builder_.add_val_float(val_float);
  builder_.add_val_u32(val_u32);
  builder_.add_val_bool(val_bool);
  builder_.add_val_u8(val_u8);
  return builder_.Finish();
}

struct DataContainer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataContainerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_RAW_DATA = 6,
    VT_INDICES = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<uint8_t> *raw_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_RAW_DATA);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_RAW_DATA) &&
           verifier.VerifyVector(raw_data()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           verifier.EndTable();
  }
};

struct DataContainerBuilder {
  typedef DataContainer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(DataContainer::VT_NAME, name);
  }
  void add_raw_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> raw_data) {
    fbb_.AddOffset(DataContainer::VT_RAW_DATA, raw_data);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(DataContainer::VT_INDICES, indices);
  }
  explicit DataContainerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataContainer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataContainer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataContainer> CreateDataContainer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> raw_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0) {
  DataContainerBuilder builder_(_fbb);
  builder_.add_indices(indices);
  builder_.add_raw_data(raw_data);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataContainer> CreateDataContainerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<uint8_t> *raw_data = nullptr,
    const std::vector<uint32_t> *indices = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto raw_data__ = raw_data ? _fbb.CreateVector<uint8_t>(*raw_data) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  return SuOS::Uds::Msg::TestUniversal::CreateDataContainer(
      _fbb,
      name__,
      raw_data__,
      indices__);
}

struct EmptySignal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmptySignalBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct EmptySignalBuilder {
  typedef EmptySignal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit EmptySignalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmptySignal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmptySignal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmptySignal> CreateEmptySignal(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  EmptySignalBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ConfigInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConfigInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DESCRIPTION = 6
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           verifier.EndTable();
  }
};

struct ConfigInfoBuilder {
  typedef ConfigInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(ConfigInfo::VT_ID, id, 0);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(ConfigInfo::VT_DESCRIPTION, description);
  }
  explicit ConfigInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ConfigInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ConfigInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ConfigInfo> CreateConfigInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0) {
  ConfigInfoBuilder builder_(_fbb);
  builder_.add_description(description);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ConfigInfo> CreateConfigInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *description = nullptr) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return SuOS::Uds::Msg::TestUniversal::CreateConfigInfo(
      _fbb,
      id,
      description__);
}

struct PayloadEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PayloadEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::TestUniversal::UdsPayload payload_type() const {
    return static_cast<SuOS::Uds::Msg::TestUniversal::UdsPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::TestUniversal::ScalarTable *payload_as_ScalarTable() const {
    return payload_type() == SuOS::Uds::Msg::TestUniversal::UdsPayload_ScalarTable ? static_cast<const SuOS::Uds::Msg::TestUniversal::ScalarTable *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::TestUniversal::DataContainer *payload_as_DataContainer() const {
    return payload_type() == SuOS::Uds::Msg::TestUniversal::UdsPayload_DataContainer ? static_cast<const SuOS::Uds::Msg::TestUniversal::DataContainer *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::TestUniversal::EmptySignal *payload_as_EmptySignal() const {
    return payload_type() == SuOS::Uds::Msg::TestUniversal::UdsPayload_EmptySignal ? static_cast<const SuOS::Uds::Msg::TestUniversal::EmptySignal *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::TestUniversal::ConfigInfo *payload_as_ConfigInfo() const {
    return payload_type() == SuOS::Uds::Msg::TestUniversal::UdsPayload_ConfigInfo ? static_cast<const SuOS::Uds::Msg::TestUniversal::ConfigInfo *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyUdsPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::TestUniversal::ScalarTable *PayloadEnvelope::payload_as<SuOS::Uds::Msg::TestUniversal::ScalarTable>() const {
  return payload_as_ScalarTable();
}

template<> inline const SuOS::Uds::Msg::TestUniversal::DataContainer *PayloadEnvelope::payload_as<SuOS::Uds::Msg::TestUniversal::DataContainer>() const {
  return payload_as_DataContainer();
}

template<> inline const SuOS::Uds::Msg::TestUniversal::EmptySignal *PayloadEnvelope::payload_as<SuOS::Uds::Msg::TestUniversal::EmptySignal>() const {
  return payload_as_EmptySignal();
}

template<> inline const SuOS::Uds::Msg::TestUniversal::ConfigInfo *PayloadEnvelope::payload_as<SuOS::Uds::Msg::TestUniversal::ConfigInfo>() const {
  return payload_as_ConfigInfo();
}

struct PayloadEnvelopeBuilder {
  typedef PayloadEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::TestUniversal::UdsPayload payload_type) {
    fbb_.AddElement<uint8_t>(PayloadEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(PayloadEnvelope::VT_PAYLOAD, payload);
  }
  explicit PayloadEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PayloadEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PayloadEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PayloadEnvelope> CreatePayloadEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::TestUniversal::UdsPayload payload_type = SuOS::Uds::Msg::TestUniversal::UdsPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  PayloadEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyUdsPayload(::flatbuffers::Verifier &verifier, const void *obj, UdsPayload type) {
  switch (type) {
    case UdsPayload_NONE: {
      return true;
    }
    case UdsPayload_ScalarTable: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::TestUniversal::ScalarTable *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_DataContainer: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::TestUniversal::DataContainer *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_EmptySignal: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::TestUniversal::EmptySignal *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_ConfigInfo: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::TestUniversal::ConfigInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyUdsPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyUdsPayload(
        verifier,  values->Get(i), types->GetEnum<UdsPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::TestUniversal::PayloadEnvelope *GetPayloadEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::TestUniversal::PayloadEnvelope>(buf);
}

inline const SuOS::Uds::Msg::TestUniversal::PayloadEnvelope *GetSizePrefixedPayloadEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::TestUniversal::PayloadEnvelope>(buf);
}

inline bool VerifyPayloadEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::TestUniversal::PayloadEnvelope>(nullptr);
}

inline bool VerifySizePrefixedPayloadEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::TestUniversal::PayloadEnvelope>(nullptr);
}

inline void FinishPayloadEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::TestUniversal::PayloadEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPayloadEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::TestUniversal::PayloadEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace TestUniversal
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_SUUDSPARTEXAMPLE_SUOS_UDS_MSG_TESTUNIVERSAL_H_
