// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERALMSGFROMMAIN_SUOS_UDS_MSG_GENERAL_H_
#define FLATBUFFERS_GENERATED_GENERALMSGFROMMAIN_SUOS_UDS_MSG_GENERAL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace General {

struct UsrStopRequest;
struct UsrStopRequestBuilder;

struct UsrStopKill;
struct UsrStopKillBuilder;

struct GeneralEnvelope_fromMain;
struct GeneralEnvelope_fromMainBuilder;

enum GeneralPayload_fromMain : uint8_t {
  GeneralPayload_fromMain_NONE = 0,
  GeneralPayload_fromMain_UsrStopRequest = 1,
  GeneralPayload_fromMain_UsrStopKill = 2,
  GeneralPayload_fromMain_MIN = GeneralPayload_fromMain_NONE,
  GeneralPayload_fromMain_MAX = GeneralPayload_fromMain_UsrStopKill
};

inline const GeneralPayload_fromMain (&EnumValuesGeneralPayload_fromMain())[3] {
  static const GeneralPayload_fromMain values[] = {
    GeneralPayload_fromMain_NONE,
    GeneralPayload_fromMain_UsrStopRequest,
    GeneralPayload_fromMain_UsrStopKill
  };
  return values;
}

inline const char * const *EnumNamesGeneralPayload_fromMain() {
  static const char * const names[4] = {
    "NONE",
    "UsrStopRequest",
    "UsrStopKill",
    nullptr
  };
  return names;
}

inline const char *EnumNameGeneralPayload_fromMain(GeneralPayload_fromMain e) {
  if (::flatbuffers::IsOutRange(e, GeneralPayload_fromMain_NONE, GeneralPayload_fromMain_UsrStopKill)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGeneralPayload_fromMain()[index];
}

template<typename T> struct GeneralPayload_fromMainTraits {
  static const GeneralPayload_fromMain enum_value = GeneralPayload_fromMain_NONE;
};

template<> struct GeneralPayload_fromMainTraits<SuOS::Uds::Msg::General::UsrStopRequest> {
  static const GeneralPayload_fromMain enum_value = GeneralPayload_fromMain_UsrStopRequest;
};

template<> struct GeneralPayload_fromMainTraits<SuOS::Uds::Msg::General::UsrStopKill> {
  static const GeneralPayload_fromMain enum_value = GeneralPayload_fromMain_UsrStopKill;
};

bool VerifyGeneralPayload_fromMain(::flatbuffers::Verifier &verifier, const void *obj, GeneralPayload_fromMain type);
bool VerifyGeneralPayload_fromMainVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct UsrStopRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsrStopRequestBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UsrStopRequestBuilder {
  typedef UsrStopRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UsrStopRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsrStopRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsrStopRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsrStopRequest> CreateUsrStopRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UsrStopRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UsrStopKill FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsrStopKillBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UsrStopKillBuilder {
  typedef UsrStopKill Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UsrStopKillBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsrStopKill> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsrStopKill>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsrStopKill> CreateUsrStopKill(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UsrStopKillBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GeneralEnvelope_fromMain FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GeneralEnvelope_fromMainBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::General::GeneralPayload_fromMain payload_type() const {
    return static_cast<SuOS::Uds::Msg::General::GeneralPayload_fromMain>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::General::UsrStopRequest *payload_as_UsrStopRequest() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_fromMain_UsrStopRequest ? static_cast<const SuOS::Uds::Msg::General::UsrStopRequest *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::General::UsrStopKill *payload_as_UsrStopKill() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_fromMain_UsrStopKill ? static_cast<const SuOS::Uds::Msg::General::UsrStopKill *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyGeneralPayload_fromMain(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::General::UsrStopRequest *GeneralEnvelope_fromMain::payload_as<SuOS::Uds::Msg::General::UsrStopRequest>() const {
  return payload_as_UsrStopRequest();
}

template<> inline const SuOS::Uds::Msg::General::UsrStopKill *GeneralEnvelope_fromMain::payload_as<SuOS::Uds::Msg::General::UsrStopKill>() const {
  return payload_as_UsrStopKill();
}

struct GeneralEnvelope_fromMainBuilder {
  typedef GeneralEnvelope_fromMain Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::General::GeneralPayload_fromMain payload_type) {
    fbb_.AddElement<uint8_t>(GeneralEnvelope_fromMain::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(GeneralEnvelope_fromMain::VT_PAYLOAD, payload);
  }
  explicit GeneralEnvelope_fromMainBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GeneralEnvelope_fromMain> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GeneralEnvelope_fromMain>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GeneralEnvelope_fromMain> CreateGeneralEnvelope_fromMain(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::General::GeneralPayload_fromMain payload_type = SuOS::Uds::Msg::General::GeneralPayload_fromMain_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  GeneralEnvelope_fromMainBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyGeneralPayload_fromMain(::flatbuffers::Verifier &verifier, const void *obj, GeneralPayload_fromMain type) {
  switch (type) {
    case GeneralPayload_fromMain_NONE: {
      return true;
    }
    case GeneralPayload_fromMain_UsrStopRequest: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::UsrStopRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GeneralPayload_fromMain_UsrStopKill: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::UsrStopKill *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyGeneralPayload_fromMainVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyGeneralPayload_fromMain(
        verifier,  values->Get(i), types->GetEnum<GeneralPayload_fromMain>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::General::GeneralEnvelope_fromMain *GetGeneralEnvelope_fromMain(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::General::GeneralEnvelope_fromMain>(buf);
}

inline const SuOS::Uds::Msg::General::GeneralEnvelope_fromMain *GetSizePrefixedGeneralEnvelope_fromMain(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::General::GeneralEnvelope_fromMain>(buf);
}

inline bool VerifyGeneralEnvelope_fromMainBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::General::GeneralEnvelope_fromMain>(nullptr);
}

inline bool VerifySizePrefixedGeneralEnvelope_fromMainBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::General::GeneralEnvelope_fromMain>(nullptr);
}

inline void FinishGeneralEnvelope_fromMainBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::General::GeneralEnvelope_fromMain> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGeneralEnvelope_fromMainBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::General::GeneralEnvelope_fromMain> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace General
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_GENERALMSGFROMMAIN_SUOS_UDS_MSG_GENERAL_H_
