// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERALMSGTOMAIN_SUOS_UDS_MSG_GENERAL_H_
#define FLATBUFFERS_GENERATED_GENERALMSGTOMAIN_SUOS_UDS_MSG_GENERAL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace General {

struct UsrStopResponse;
struct UsrStopResponseBuilder;

struct onUsrError;
struct onUsrErrorBuilder;

struct GeneralEnvelope_toMain;
struct GeneralEnvelope_toMainBuilder;

enum GeneralPayload_toMain : uint8_t {
  GeneralPayload_toMain_NONE = 0,
  GeneralPayload_toMain_UsrStopResponse = 1,
  GeneralPayload_toMain_onUsrError = 2,
  GeneralPayload_toMain_MIN = GeneralPayload_toMain_NONE,
  GeneralPayload_toMain_MAX = GeneralPayload_toMain_onUsrError
};

inline const GeneralPayload_toMain (&EnumValuesGeneralPayload_toMain())[3] {
  static const GeneralPayload_toMain values[] = {
    GeneralPayload_toMain_NONE,
    GeneralPayload_toMain_UsrStopResponse,
    GeneralPayload_toMain_onUsrError
  };
  return values;
}

inline const char * const *EnumNamesGeneralPayload_toMain() {
  static const char * const names[4] = {
    "NONE",
    "UsrStopResponse",
    "onUsrError",
    nullptr
  };
  return names;
}

inline const char *EnumNameGeneralPayload_toMain(GeneralPayload_toMain e) {
  if (::flatbuffers::IsOutRange(e, GeneralPayload_toMain_NONE, GeneralPayload_toMain_onUsrError)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGeneralPayload_toMain()[index];
}

template<typename T> struct GeneralPayload_toMainTraits {
  static const GeneralPayload_toMain enum_value = GeneralPayload_toMain_NONE;
};

template<> struct GeneralPayload_toMainTraits<SuOS::Uds::Msg::General::UsrStopResponse> {
  static const GeneralPayload_toMain enum_value = GeneralPayload_toMain_UsrStopResponse;
};

template<> struct GeneralPayload_toMainTraits<SuOS::Uds::Msg::General::onUsrError> {
  static const GeneralPayload_toMain enum_value = GeneralPayload_toMain_onUsrError;
};

bool VerifyGeneralPayload_toMain(::flatbuffers::Verifier &verifier, const void *obj, GeneralPayload_toMain type);
bool VerifyGeneralPayload_toMainVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct UsrStopResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsrStopResponseBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UsrStopResponseBuilder {
  typedef UsrStopResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UsrStopResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsrStopResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsrStopResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsrStopResponse> CreateUsrStopResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UsrStopResponseBuilder builder_(_fbb);
  return builder_.Finish();
}

struct onUsrError FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef onUsrErrorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_MSG = 6
  };
  uint32_t code() const {
    return GetField<uint32_t>(VT_CODE, 0);
  }
  const ::flatbuffers::String *msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MSG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CODE, 4) &&
           VerifyOffset(verifier, VT_MSG) &&
           verifier.VerifyString(msg()) &&
           verifier.EndTable();
  }
};

struct onUsrErrorBuilder {
  typedef onUsrError Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(uint32_t code) {
    fbb_.AddElement<uint32_t>(onUsrError::VT_CODE, code, 0);
  }
  void add_msg(::flatbuffers::Offset<::flatbuffers::String> msg) {
    fbb_.AddOffset(onUsrError::VT_MSG, msg);
  }
  explicit onUsrErrorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<onUsrError> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<onUsrError>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<onUsrError> CreateonUsrError(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> msg = 0) {
  onUsrErrorBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_code(code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<onUsrError> CreateonUsrErrorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t code = 0,
    const char *msg = nullptr) {
  auto msg__ = msg ? _fbb.CreateString(msg) : 0;
  return SuOS::Uds::Msg::General::CreateonUsrError(
      _fbb,
      code,
      msg__);
}

struct GeneralEnvelope_toMain FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GeneralEnvelope_toMainBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::General::GeneralPayload_toMain payload_type() const {
    return static_cast<SuOS::Uds::Msg::General::GeneralPayload_toMain>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::General::UsrStopResponse *payload_as_UsrStopResponse() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_toMain_UsrStopResponse ? static_cast<const SuOS::Uds::Msg::General::UsrStopResponse *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::General::onUsrError *payload_as_onUsrError() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_toMain_onUsrError ? static_cast<const SuOS::Uds::Msg::General::onUsrError *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyGeneralPayload_toMain(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::General::UsrStopResponse *GeneralEnvelope_toMain::payload_as<SuOS::Uds::Msg::General::UsrStopResponse>() const {
  return payload_as_UsrStopResponse();
}

template<> inline const SuOS::Uds::Msg::General::onUsrError *GeneralEnvelope_toMain::payload_as<SuOS::Uds::Msg::General::onUsrError>() const {
  return payload_as_onUsrError();
}

struct GeneralEnvelope_toMainBuilder {
  typedef GeneralEnvelope_toMain Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::General::GeneralPayload_toMain payload_type) {
    fbb_.AddElement<uint8_t>(GeneralEnvelope_toMain::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(GeneralEnvelope_toMain::VT_PAYLOAD, payload);
  }
  explicit GeneralEnvelope_toMainBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GeneralEnvelope_toMain> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GeneralEnvelope_toMain>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GeneralEnvelope_toMain> CreateGeneralEnvelope_toMain(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::General::GeneralPayload_toMain payload_type = SuOS::Uds::Msg::General::GeneralPayload_toMain_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  GeneralEnvelope_toMainBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyGeneralPayload_toMain(::flatbuffers::Verifier &verifier, const void *obj, GeneralPayload_toMain type) {
  switch (type) {
    case GeneralPayload_toMain_NONE: {
      return true;
    }
    case GeneralPayload_toMain_UsrStopResponse: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::UsrStopResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GeneralPayload_toMain_onUsrError: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::onUsrError *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyGeneralPayload_toMainVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyGeneralPayload_toMain(
        verifier,  values->Get(i), types->GetEnum<GeneralPayload_toMain>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::General::GeneralEnvelope_toMain *GetGeneralEnvelope_toMain(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::General::GeneralEnvelope_toMain>(buf);
}

inline const SuOS::Uds::Msg::General::GeneralEnvelope_toMain *GetSizePrefixedGeneralEnvelope_toMain(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::General::GeneralEnvelope_toMain>(buf);
}

inline bool VerifyGeneralEnvelope_toMainBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::General::GeneralEnvelope_toMain>(nullptr);
}

inline bool VerifySizePrefixedGeneralEnvelope_toMainBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::General::GeneralEnvelope_toMain>(nullptr);
}

inline void FinishGeneralEnvelope_toMainBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::General::GeneralEnvelope_toMain> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGeneralEnvelope_toMainBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::General::GeneralEnvelope_toMain> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace General
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_GENERALMSGTOMAIN_SUOS_UDS_MSG_GENERAL_H_
