// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENERALMSG_SUOS_UDS_MSG_GENERAL_H_
#define FLATBUFFERS_GENERATED_GENERALMSG_SUOS_UDS_MSG_GENERAL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace General {

struct Heartbeat;
struct HeartbeatBuilder;

struct UsrStopRequest;
struct UsrStopRequestBuilder;

struct UsrStopResponse;
struct UsrStopResponseBuilder;

struct UsrStopKill;
struct UsrStopKillBuilder;

struct GeneralEnvelope;
struct GeneralEnvelopeBuilder;

enum GeneralPayload : uint8_t {
  GeneralPayload_NONE = 0,
  GeneralPayload_Heartbeat = 1,
  GeneralPayload_UsrStopRequest = 2,
  GeneralPayload_UsrStopResponse = 3,
  GeneralPayload_UsrStopKill = 4,
  GeneralPayload_MIN = GeneralPayload_NONE,
  GeneralPayload_MAX = GeneralPayload_UsrStopKill
};

inline const GeneralPayload (&EnumValuesGeneralPayload())[5] {
  static const GeneralPayload values[] = {
    GeneralPayload_NONE,
    GeneralPayload_Heartbeat,
    GeneralPayload_UsrStopRequest,
    GeneralPayload_UsrStopResponse,
    GeneralPayload_UsrStopKill
  };
  return values;
}

inline const char * const *EnumNamesGeneralPayload() {
  static const char * const names[6] = {
    "NONE",
    "Heartbeat",
    "UsrStopRequest",
    "UsrStopResponse",
    "UsrStopKill",
    nullptr
  };
  return names;
}

inline const char *EnumNameGeneralPayload(GeneralPayload e) {
  if (::flatbuffers::IsOutRange(e, GeneralPayload_NONE, GeneralPayload_UsrStopKill)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGeneralPayload()[index];
}

template<typename T> struct GeneralPayloadTraits {
  static const GeneralPayload enum_value = GeneralPayload_NONE;
};

template<> struct GeneralPayloadTraits<SuOS::Uds::Msg::General::Heartbeat> {
  static const GeneralPayload enum_value = GeneralPayload_Heartbeat;
};

template<> struct GeneralPayloadTraits<SuOS::Uds::Msg::General::UsrStopRequest> {
  static const GeneralPayload enum_value = GeneralPayload_UsrStopRequest;
};

template<> struct GeneralPayloadTraits<SuOS::Uds::Msg::General::UsrStopResponse> {
  static const GeneralPayload enum_value = GeneralPayload_UsrStopResponse;
};

template<> struct GeneralPayloadTraits<SuOS::Uds::Msg::General::UsrStopKill> {
  static const GeneralPayload enum_value = GeneralPayload_UsrStopKill;
};

bool VerifyGeneralPayload(::flatbuffers::Verifier &verifier, const void *obj, GeneralPayload type);
bool VerifyGeneralPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Heartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct HeartbeatBuilder {
  typedef Heartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit HeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Heartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Heartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  HeartbeatBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UsrStopRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsrStopRequestBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UsrStopRequestBuilder {
  typedef UsrStopRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UsrStopRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsrStopRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsrStopRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsrStopRequest> CreateUsrStopRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UsrStopRequestBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UsrStopResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsrStopResponseBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UsrStopResponseBuilder {
  typedef UsrStopResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UsrStopResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsrStopResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsrStopResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsrStopResponse> CreateUsrStopResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UsrStopResponseBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UsrStopKill FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsrStopKillBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UsrStopKillBuilder {
  typedef UsrStopKill Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UsrStopKillBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsrStopKill> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsrStopKill>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsrStopKill> CreateUsrStopKill(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UsrStopKillBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GeneralEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GeneralEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::General::GeneralPayload payload_type() const {
    return static_cast<SuOS::Uds::Msg::General::GeneralPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::General::Heartbeat *payload_as_Heartbeat() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_Heartbeat ? static_cast<const SuOS::Uds::Msg::General::Heartbeat *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::General::UsrStopRequest *payload_as_UsrStopRequest() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_UsrStopRequest ? static_cast<const SuOS::Uds::Msg::General::UsrStopRequest *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::General::UsrStopResponse *payload_as_UsrStopResponse() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_UsrStopResponse ? static_cast<const SuOS::Uds::Msg::General::UsrStopResponse *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::General::UsrStopKill *payload_as_UsrStopKill() const {
    return payload_type() == SuOS::Uds::Msg::General::GeneralPayload_UsrStopKill ? static_cast<const SuOS::Uds::Msg::General::UsrStopKill *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyGeneralPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::General::Heartbeat *GeneralEnvelope::payload_as<SuOS::Uds::Msg::General::Heartbeat>() const {
  return payload_as_Heartbeat();
}

template<> inline const SuOS::Uds::Msg::General::UsrStopRequest *GeneralEnvelope::payload_as<SuOS::Uds::Msg::General::UsrStopRequest>() const {
  return payload_as_UsrStopRequest();
}

template<> inline const SuOS::Uds::Msg::General::UsrStopResponse *GeneralEnvelope::payload_as<SuOS::Uds::Msg::General::UsrStopResponse>() const {
  return payload_as_UsrStopResponse();
}

template<> inline const SuOS::Uds::Msg::General::UsrStopKill *GeneralEnvelope::payload_as<SuOS::Uds::Msg::General::UsrStopKill>() const {
  return payload_as_UsrStopKill();
}

struct GeneralEnvelopeBuilder {
  typedef GeneralEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::General::GeneralPayload payload_type) {
    fbb_.AddElement<uint8_t>(GeneralEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(GeneralEnvelope::VT_PAYLOAD, payload);
  }
  explicit GeneralEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GeneralEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GeneralEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GeneralEnvelope> CreateGeneralEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::General::GeneralPayload payload_type = SuOS::Uds::Msg::General::GeneralPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  GeneralEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyGeneralPayload(::flatbuffers::Verifier &verifier, const void *obj, GeneralPayload type) {
  switch (type) {
    case GeneralPayload_NONE: {
      return true;
    }
    case GeneralPayload_Heartbeat: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::Heartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GeneralPayload_UsrStopRequest: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::UsrStopRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GeneralPayload_UsrStopResponse: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::UsrStopResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GeneralPayload_UsrStopKill: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::General::UsrStopKill *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyGeneralPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyGeneralPayload(
        verifier,  values->Get(i), types->GetEnum<GeneralPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::General::GeneralEnvelope *GetGeneralEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::General::GeneralEnvelope>(buf);
}

inline const SuOS::Uds::Msg::General::GeneralEnvelope *GetSizePrefixedGeneralEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::General::GeneralEnvelope>(buf);
}

inline bool VerifyGeneralEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::General::GeneralEnvelope>(nullptr);
}

inline bool VerifySizePrefixedGeneralEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::General::GeneralEnvelope>(nullptr);
}

inline void FinishGeneralEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::General::GeneralEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGeneralEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::General::GeneralEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace General
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_GENERALMSG_SUOS_UDS_MSG_GENERAL_H_
