// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUUDSMSG_SUOS_UDS_Msg_H_
#define FLATBUFFERS_GENERATED_SUUDSMSG_SUOS_UDS_Msg_H_

#include "flatbuffers/flatbuffers.h"

namespace SuOS { 
namespace Uds {
namespace Msg {

struct MessageEnvelope;
struct MessageEnvelopeBuilder;
struct MessageEnvelopeT;

struct MessageEnvelopeT : public flatbuffers::NativeTable {
  typedef MessageEnvelope TableType;
  uint32_t sender_usr;
  uint32_t sender_part;
  uint32_t receiver_usr;
  uint32_t receiver_part;
  uint32_t cmd_id;
  std::vector<uint8_t> payload;
  MessageEnvelopeT()
      : sender_usr(0),
        sender_part(0),
        receiver_usr(0),
        receiver_part(0),
        cmd_id(0) {
  }
};

struct MessageEnvelope FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageEnvelopeT NativeTableType;
  typedef MessageEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_USR = 4,
    VT_SENDER_PART = 6,
    VT_RECEIVER_USR = 8,
    VT_RECEIVER_PART = 10,
    VT_CMD_ID = 12,
    VT_PAYLOAD = 14
  };
  uint32_t sender_usr() const {
    return GetField<uint32_t>(VT_SENDER_USR, 0);
  }
  uint32_t sender_part() const {
    return GetField<uint32_t>(VT_SENDER_PART, 0);
  }
  uint32_t receiver_usr() const {
    return GetField<uint32_t>(VT_RECEIVER_USR, 0);
  }
  uint32_t receiver_part() const {
    return GetField<uint32_t>(VT_RECEIVER_PART, 0);
  }
  uint32_t cmd_id() const {
    return GetField<uint32_t>(VT_CMD_ID, 0);
  }
  const flatbuffers::Vector<uint8_t> *payload() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_PAYLOAD);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SENDER_USR) &&
           VerifyField<uint32_t>(verifier, VT_SENDER_PART) &&
           VerifyField<uint32_t>(verifier, VT_RECEIVER_USR) &&
           VerifyField<uint32_t>(verifier, VT_RECEIVER_PART) &&
           VerifyField<uint32_t>(verifier, VT_CMD_ID) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.EndTable();
  }
  MessageEnvelopeT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MessageEnvelopeT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<MessageEnvelope> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MessageEnvelopeT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MessageEnvelopeBuilder {
  typedef MessageEnvelope Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sender_usr(uint32_t sender_usr) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_SENDER_USR, sender_usr, 0);
  }
  void add_sender_part(uint32_t sender_part) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_SENDER_PART, sender_part, 0);
  }
  void add_receiver_usr(uint32_t receiver_usr) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_RECEIVER_USR, receiver_usr, 0);
  }
  void add_receiver_part(uint32_t receiver_part) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_RECEIVER_PART, receiver_part, 0);
  }
  void add_cmd_id(uint32_t cmd_id) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_CMD_ID, cmd_id, 0);
  }
  void add_payload(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> payload) {
    fbb_.AddOffset(MessageEnvelope::VT_PAYLOAD, payload);
  }
  explicit MessageEnvelopeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<MessageEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MessageEnvelope>(end);
    return o;
  }
};

inline flatbuffers::Offset<MessageEnvelope> CreateMessageEnvelope(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sender_usr = 0,
    uint32_t sender_part = 0,
    uint32_t receiver_usr = 0,
    uint32_t receiver_part = 0,
    uint32_t cmd_id = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> payload = 0) {
  MessageEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_cmd_id(cmd_id);
  builder_.add_receiver_part(receiver_part);
  builder_.add_receiver_usr(receiver_usr);
  builder_.add_sender_part(sender_part);
  builder_.add_sender_usr(sender_usr);
  return builder_.Finish();
}

inline flatbuffers::Offset<MessageEnvelope> CreateMessageEnvelopeDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sender_usr = 0,
    uint32_t sender_part = 0,
    uint32_t receiver_usr = 0,
    uint32_t receiver_part = 0,
    uint32_t cmd_id = 0,
    const std::vector<uint8_t> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<uint8_t>(*payload) : 0;
  return SuOS::Uds::Msg::CreateMessageEnvelope(
      _fbb,
      sender_usr,
      sender_part,
      receiver_usr,
      receiver_part,
      cmd_id,
      payload__);
}

flatbuffers::Offset<MessageEnvelope> CreateMessageEnvelope(flatbuffers::FlatBufferBuilder &_fbb, const MessageEnvelopeT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline MessageEnvelopeT *MessageEnvelope::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<SuOS::Uds::Msg::MessageEnvelopeT> _o = std::unique_ptr<SuOS::Uds::Msg::MessageEnvelopeT>(new MessageEnvelopeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MessageEnvelope::UnPackTo(MessageEnvelopeT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = sender_usr(); _o->sender_usr = _e; }
  { auto _e = sender_part(); _o->sender_part = _e; }
  { auto _e = receiver_usr(); _o->receiver_usr = _e; }
  { auto _e = receiver_part(); _o->receiver_part = _e; }
  { auto _e = cmd_id(); _o->cmd_id = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->payload[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<MessageEnvelope> MessageEnvelope::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MessageEnvelopeT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMessageEnvelope(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<MessageEnvelope> CreateMessageEnvelope(flatbuffers::FlatBufferBuilder &_fbb, const MessageEnvelopeT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MessageEnvelopeT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _sender_usr = _o->sender_usr;
  auto _sender_part = _o->sender_part;
  auto _receiver_usr = _o->receiver_usr;
  auto _receiver_part = _o->receiver_part;
  auto _cmd_id = _o->cmd_id;
  auto _payload = _o->payload.size() ? _fbb.CreateVector(_o->payload) : 0;
  return SuOS::Uds::Msg::CreateMessageEnvelope(
      _fbb,
      _sender_usr,
      _sender_part,
      _receiver_usr,
      _receiver_part,
      _cmd_id,
      _payload);
}

inline const SuOS::Uds::Msg::MessageEnvelope *GetMessageEnvelope(const void *buf) {
  return flatbuffers::GetRoot<SuOS::Uds::Msg::MessageEnvelope>(buf);
}

inline const SuOS::Uds::Msg::MessageEnvelope *GetSizePrefixedMessageEnvelope(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::MessageEnvelope>(buf);
}

inline bool VerifyMessageEnvelopeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::MessageEnvelope>(nullptr);
}

inline bool VerifySizePrefixedMessageEnvelopeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::MessageEnvelope>(nullptr);
}

inline void FinishMessageEnvelopeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SuOS::Uds::Msg::MessageEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageEnvelopeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SuOS::Uds::Msg::MessageEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<SuOS::Uds::Msg::MessageEnvelopeT> UnPackMessageEnvelope(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SuOS::Uds::Msg::MessageEnvelopeT>(GetMessageEnvelope(buf)->UnPack(res));
}

inline std::unique_ptr<SuOS::Uds::Msg::MessageEnvelopeT> UnPackSizePrefixedMessageEnvelope(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<SuOS::Uds::Msg::MessageEnvelopeT>(GetSizePrefixedMessageEnvelope(buf)->UnPack(res));
}

}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_SUUDSMSG_SUOS_UDS_Msg_H_
