// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUUDSMSG_SUOS_UDS_MSG_H_
#define FLATBUFFERS_GENERATED_SUUDSMSG_SUOS_UDS_MSG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {

struct MessageEnvelope;
struct MessageEnvelopeBuilder;

struct MessageEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_USR = 4,
    VT_SENDER_PART = 6,
    VT_RECEIVER_USR = 8,
    VT_RECEIVER_PART = 10,
    VT_CMD_ID = 12,
    VT_PAYLOAD = 14
  };
  uint32_t sender_usr() const {
    return GetField<uint32_t>(VT_SENDER_USR, 0);
  }
  uint32_t sender_part() const {
    return GetField<uint32_t>(VT_SENDER_PART, 0);
  }
  uint32_t receiver_usr() const {
    return GetField<uint32_t>(VT_RECEIVER_USR, 0);
  }
  uint32_t receiver_part() const {
    return GetField<uint32_t>(VT_RECEIVER_PART, 0);
  }
  uint32_t cmd_id() const {
    return GetField<uint32_t>(VT_CMD_ID, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SENDER_USR, 4) &&
           VerifyField<uint32_t>(verifier, VT_SENDER_PART, 4) &&
           VerifyField<uint32_t>(verifier, VT_RECEIVER_USR, 4) &&
           VerifyField<uint32_t>(verifier, VT_RECEIVER_PART, 4) &&
           VerifyField<uint32_t>(verifier, VT_CMD_ID, 4) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.EndTable();
  }
};

struct MessageEnvelopeBuilder {
  typedef MessageEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sender_usr(uint32_t sender_usr) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_SENDER_USR, sender_usr, 0);
  }
  void add_sender_part(uint32_t sender_part) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_SENDER_PART, sender_part, 0);
  }
  void add_receiver_usr(uint32_t receiver_usr) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_RECEIVER_USR, receiver_usr, 0);
  }
  void add_receiver_part(uint32_t receiver_part) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_RECEIVER_PART, receiver_part, 0);
  }
  void add_cmd_id(uint32_t cmd_id) {
    fbb_.AddElement<uint32_t>(MessageEnvelope::VT_CMD_ID, cmd_id, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload) {
    fbb_.AddOffset(MessageEnvelope::VT_PAYLOAD, payload);
  }
  explicit MessageEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MessageEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MessageEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MessageEnvelope> CreateMessageEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sender_usr = 0,
    uint32_t sender_part = 0,
    uint32_t receiver_usr = 0,
    uint32_t receiver_part = 0,
    uint32_t cmd_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload = 0) {
  MessageEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_cmd_id(cmd_id);
  builder_.add_receiver_part(receiver_part);
  builder_.add_receiver_usr(receiver_usr);
  builder_.add_sender_part(sender_part);
  builder_.add_sender_usr(sender_usr);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MessageEnvelope> CreateMessageEnvelopeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t sender_usr = 0,
    uint32_t sender_part = 0,
    uint32_t receiver_usr = 0,
    uint32_t receiver_part = 0,
    uint32_t cmd_id = 0,
    const std::vector<uint8_t> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<uint8_t>(*payload) : 0;
  return SuOS::Uds::Msg::CreateMessageEnvelope(
      _fbb,
      sender_usr,
      sender_part,
      receiver_usr,
      receiver_part,
      cmd_id,
      payload__);
}

inline const SuOS::Uds::Msg::MessageEnvelope *GetMessageEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::MessageEnvelope>(buf);
}

inline const SuOS::Uds::Msg::MessageEnvelope *GetSizePrefixedMessageEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::MessageEnvelope>(buf);
}

inline bool VerifyMessageEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::MessageEnvelope>(nullptr);
}

inline bool VerifySizePrefixedMessageEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::MessageEnvelope>(nullptr);
}

inline void FinishMessageEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::MessageEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::MessageEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_SUUDSMSG_SUOS_UDS_MSG_H_
