// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUUDSPARTEXAMPLE_SUOS_UDS_MSG_PARTEXAMPLE_H_
#define FLATBUFFERS_GENERATED_SUUDSPARTEXAMPLE_SUOS_UDS_MSG_PARTEXAMPLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace PartExample {

struct NoArgs;
struct NoArgsBuilder;

struct CmdRequest;
struct CmdRequestBuilder;

struct CmdResponse;
struct CmdResponseBuilder;

struct EventNotify;
struct EventNotifyBuilder;

struct ErrorResponse;
struct ErrorResponseBuilder;

struct PayloadEnvelope;
struct PayloadEnvelopeBuilder;

enum UdsPayload : uint8_t {
  UdsPayload_NONE = 0,
  UdsPayload_NoArgs = 1,
  UdsPayload_CmdRequest = 2,
  UdsPayload_CmdResponse = 3,
  UdsPayload_EventNotify = 4,
  UdsPayload_ErrorResponse = 5,
  UdsPayload_MIN = UdsPayload_NONE,
  UdsPayload_MAX = UdsPayload_ErrorResponse
};

inline const UdsPayload (&EnumValuesUdsPayload())[6] {
  static const UdsPayload values[] = {
    UdsPayload_NONE,
    UdsPayload_NoArgs,
    UdsPayload_CmdRequest,
    UdsPayload_CmdResponse,
    UdsPayload_EventNotify,
    UdsPayload_ErrorResponse
  };
  return values;
}

inline const char * const *EnumNamesUdsPayload() {
  static const char * const names[7] = {
    "NONE",
    "NoArgs",
    "CmdRequest",
    "CmdResponse",
    "EventNotify",
    "ErrorResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameUdsPayload(UdsPayload e) {
  if (::flatbuffers::IsOutRange(e, UdsPayload_NONE, UdsPayload_ErrorResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesUdsPayload()[index];
}

template<typename T> struct UdsPayloadTraits {
  static const UdsPayload enum_value = UdsPayload_NONE;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::PartExample::NoArgs> {
  static const UdsPayload enum_value = UdsPayload_NoArgs;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::PartExample::CmdRequest> {
  static const UdsPayload enum_value = UdsPayload_CmdRequest;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::PartExample::CmdResponse> {
  static const UdsPayload enum_value = UdsPayload_CmdResponse;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::PartExample::EventNotify> {
  static const UdsPayload enum_value = UdsPayload_EventNotify;
};

template<> struct UdsPayloadTraits<SuOS::Uds::Msg::PartExample::ErrorResponse> {
  static const UdsPayload enum_value = UdsPayload_ErrorResponse;
};

bool VerifyUdsPayload(::flatbuffers::Verifier &verifier, const void *obj, UdsPayload type);
bool VerifyUdsPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct NoArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NoArgsBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct NoArgsBuilder {
  typedef NoArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit NoArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NoArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NoArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NoArgs> CreateNoArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  NoArgsBuilder builder_(_fbb);
  return builder_.Finish();
}

struct CmdRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ_NO = 4,
    VT_PARAMETERS = 6
  };
  uint32_t seq_no() const {
    return GetField<uint32_t>(VT_SEQ_NO, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *parameters() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PARAMETERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SEQ_NO, 4) &&
           VerifyOffset(verifier, VT_PARAMETERS) &&
           verifier.VerifyVector(parameters()) &&
           verifier.EndTable();
  }
};

struct CmdRequestBuilder {
  typedef CmdRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq_no(uint32_t seq_no) {
    fbb_.AddElement<uint32_t>(CmdRequest::VT_SEQ_NO, seq_no, 0);
  }
  void add_parameters(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> parameters) {
    fbb_.AddOffset(CmdRequest::VT_PARAMETERS, parameters);
  }
  explicit CmdRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdRequest> CreateCmdRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seq_no = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> parameters = 0) {
  CmdRequestBuilder builder_(_fbb);
  builder_.add_parameters(parameters);
  builder_.add_seq_no(seq_no);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CmdRequest> CreateCmdRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seq_no = 0,
    const std::vector<uint8_t> *parameters = nullptr) {
  auto parameters__ = parameters ? _fbb.CreateVector<uint8_t>(*parameters) : 0;
  return SuOS::Uds::Msg::PartExample::CreateCmdRequest(
      _fbb,
      seq_no,
      parameters__);
}

struct CmdResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ_NO = 4,
    VT_RESULT_CODE = 6,
    VT_DATA = 8
  };
  uint32_t seq_no() const {
    return GetField<uint32_t>(VT_SEQ_NO, 0);
  }
  uint32_t result_code() const {
    return GetField<uint32_t>(VT_RESULT_CODE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SEQ_NO, 4) &&
           VerifyField<uint32_t>(verifier, VT_RESULT_CODE, 4) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct CmdResponseBuilder {
  typedef CmdResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq_no(uint32_t seq_no) {
    fbb_.AddElement<uint32_t>(CmdResponse::VT_SEQ_NO, seq_no, 0);
  }
  void add_result_code(uint32_t result_code) {
    fbb_.AddElement<uint32_t>(CmdResponse::VT_RESULT_CODE, result_code, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(CmdResponse::VT_DATA, data);
  }
  explicit CmdResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdResponse> CreateCmdResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seq_no = 0,
    uint32_t result_code = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  CmdResponseBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_result_code(result_code);
  builder_.add_seq_no(seq_no);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CmdResponse> CreateCmdResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seq_no = 0,
    uint32_t result_code = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return SuOS::Uds::Msg::PartExample::CreateCmdResponse(
      _fbb,
      seq_no,
      result_code,
      data__);
}

struct EventNotify FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventNotifyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_ID = 4,
    VT_SEVERITY = 6,
    VT_DETAIL = 8
  };
  uint32_t event_id() const {
    return GetField<uint32_t>(VT_EVENT_ID, 0);
  }
  uint32_t severity() const {
    return GetField<uint32_t>(VT_SEVERITY, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *detail() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DETAIL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_EVENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_SEVERITY, 4) &&
           VerifyOffset(verifier, VT_DETAIL) &&
           verifier.VerifyVector(detail()) &&
           verifier.EndTable();
  }
};

struct EventNotifyBuilder {
  typedef EventNotify Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_event_id(uint32_t event_id) {
    fbb_.AddElement<uint32_t>(EventNotify::VT_EVENT_ID, event_id, 0);
  }
  void add_severity(uint32_t severity) {
    fbb_.AddElement<uint32_t>(EventNotify::VT_SEVERITY, severity, 0);
  }
  void add_detail(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> detail) {
    fbb_.AddOffset(EventNotify::VT_DETAIL, detail);
  }
  explicit EventNotifyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventNotify> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventNotify>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventNotify> CreateEventNotify(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t event_id = 0,
    uint32_t severity = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> detail = 0) {
  EventNotifyBuilder builder_(_fbb);
  builder_.add_detail(detail);
  builder_.add_severity(severity);
  builder_.add_event_id(event_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventNotify> CreateEventNotifyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t event_id = 0,
    uint32_t severity = 0,
    const std::vector<uint8_t> *detail = nullptr) {
  auto detail__ = detail ? _fbb.CreateVector<uint8_t>(*detail) : 0;
  return SuOS::Uds::Msg::PartExample::CreateEventNotify(
      _fbb,
      event_id,
      severity,
      detail__);
}

struct ErrorResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ_NO = 4,
    VT_ERROR_CODE = 6,
    VT_ERROR_MSG = 8
  };
  uint32_t seq_no() const {
    return GetField<uint32_t>(VT_SEQ_NO, 0);
  }
  uint32_t error_code() const {
    return GetField<uint32_t>(VT_ERROR_CODE, 0);
  }
  const ::flatbuffers::String *error_msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MSG);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SEQ_NO, 4) &&
           VerifyField<uint32_t>(verifier, VT_ERROR_CODE, 4) &&
           VerifyOffset(verifier, VT_ERROR_MSG) &&
           verifier.VerifyString(error_msg()) &&
           verifier.EndTable();
  }
};

struct ErrorResponseBuilder {
  typedef ErrorResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq_no(uint32_t seq_no) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_SEQ_NO, seq_no, 0);
  }
  void add_error_code(uint32_t error_code) {
    fbb_.AddElement<uint32_t>(ErrorResponse::VT_ERROR_CODE, error_code, 0);
  }
  void add_error_msg(::flatbuffers::Offset<::flatbuffers::String> error_msg) {
    fbb_.AddOffset(ErrorResponse::VT_ERROR_MSG, error_msg);
  }
  explicit ErrorResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ErrorResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ErrorResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seq_no = 0,
    uint32_t error_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error_msg = 0) {
  ErrorResponseBuilder builder_(_fbb);
  builder_.add_error_msg(error_msg);
  builder_.add_error_code(error_code);
  builder_.add_seq_no(seq_no);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ErrorResponse> CreateErrorResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seq_no = 0,
    uint32_t error_code = 0,
    const char *error_msg = nullptr) {
  auto error_msg__ = error_msg ? _fbb.CreateString(error_msg) : 0;
  return SuOS::Uds::Msg::PartExample::CreateErrorResponse(
      _fbb,
      seq_no,
      error_code,
      error_msg__);
}

struct PayloadEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PayloadEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::PartExample::UdsPayload payload_type() const {
    return static_cast<SuOS::Uds::Msg::PartExample::UdsPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::PartExample::NoArgs *payload_as_NoArgs() const {
    return payload_type() == SuOS::Uds::Msg::PartExample::UdsPayload_NoArgs ? static_cast<const SuOS::Uds::Msg::PartExample::NoArgs *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::PartExample::CmdRequest *payload_as_CmdRequest() const {
    return payload_type() == SuOS::Uds::Msg::PartExample::UdsPayload_CmdRequest ? static_cast<const SuOS::Uds::Msg::PartExample::CmdRequest *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::PartExample::CmdResponse *payload_as_CmdResponse() const {
    return payload_type() == SuOS::Uds::Msg::PartExample::UdsPayload_CmdResponse ? static_cast<const SuOS::Uds::Msg::PartExample::CmdResponse *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::PartExample::EventNotify *payload_as_EventNotify() const {
    return payload_type() == SuOS::Uds::Msg::PartExample::UdsPayload_EventNotify ? static_cast<const SuOS::Uds::Msg::PartExample::EventNotify *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::PartExample::ErrorResponse *payload_as_ErrorResponse() const {
    return payload_type() == SuOS::Uds::Msg::PartExample::UdsPayload_ErrorResponse ? static_cast<const SuOS::Uds::Msg::PartExample::ErrorResponse *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyUdsPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::PartExample::NoArgs *PayloadEnvelope::payload_as<SuOS::Uds::Msg::PartExample::NoArgs>() const {
  return payload_as_NoArgs();
}

template<> inline const SuOS::Uds::Msg::PartExample::CmdRequest *PayloadEnvelope::payload_as<SuOS::Uds::Msg::PartExample::CmdRequest>() const {
  return payload_as_CmdRequest();
}

template<> inline const SuOS::Uds::Msg::PartExample::CmdResponse *PayloadEnvelope::payload_as<SuOS::Uds::Msg::PartExample::CmdResponse>() const {
  return payload_as_CmdResponse();
}

template<> inline const SuOS::Uds::Msg::PartExample::EventNotify *PayloadEnvelope::payload_as<SuOS::Uds::Msg::PartExample::EventNotify>() const {
  return payload_as_EventNotify();
}

template<> inline const SuOS::Uds::Msg::PartExample::ErrorResponse *PayloadEnvelope::payload_as<SuOS::Uds::Msg::PartExample::ErrorResponse>() const {
  return payload_as_ErrorResponse();
}

struct PayloadEnvelopeBuilder {
  typedef PayloadEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::PartExample::UdsPayload payload_type) {
    fbb_.AddElement<uint8_t>(PayloadEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(PayloadEnvelope::VT_PAYLOAD, payload);
  }
  explicit PayloadEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PayloadEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PayloadEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PayloadEnvelope> CreatePayloadEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::PartExample::UdsPayload payload_type = SuOS::Uds::Msg::PartExample::UdsPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  PayloadEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyUdsPayload(::flatbuffers::Verifier &verifier, const void *obj, UdsPayload type) {
  switch (type) {
    case UdsPayload_NONE: {
      return true;
    }
    case UdsPayload_NoArgs: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::PartExample::NoArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_CmdRequest: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::PartExample::CmdRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_CmdResponse: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::PartExample::CmdResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_EventNotify: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::PartExample::EventNotify *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case UdsPayload_ErrorResponse: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::PartExample::ErrorResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyUdsPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyUdsPayload(
        verifier,  values->Get(i), types->GetEnum<UdsPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::PartExample::PayloadEnvelope *GetPayloadEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::PartExample::PayloadEnvelope>(buf);
}

inline const SuOS::Uds::Msg::PartExample::PayloadEnvelope *GetSizePrefixedPayloadEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::PartExample::PayloadEnvelope>(buf);
}

inline bool VerifyPayloadEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::PartExample::PayloadEnvelope>(nullptr);
}

inline bool VerifySizePrefixedPayloadEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::PartExample::PayloadEnvelope>(nullptr);
}

inline void FinishPayloadEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::PartExample::PayloadEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPayloadEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::PartExample::PayloadEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace PartExample
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_SUUDSPARTEXAMPLE_SUOS_UDS_MSG_PARTEXAMPLE_H_
