// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROUTERMSGTOROUTER_SUOS_UDS_MSG_ROUTER_H_
#define FLATBUFFERS_GENERATED_ROUTERMSGTOROUTER_SUOS_UDS_MSG_ROUTER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace Router {

struct enableAppRegister;
struct enableAppRegisterBuilder;

struct RouterEnvelope_toRouter;
struct RouterEnvelope_toRouterBuilder;

enum RouterPayload_toRouter : uint8_t {
  RouterPayload_toRouter_NONE = 0,
  RouterPayload_toRouter_enableAppRegister = 1,
  RouterPayload_toRouter_MIN = RouterPayload_toRouter_NONE,
  RouterPayload_toRouter_MAX = RouterPayload_toRouter_enableAppRegister
};

inline const RouterPayload_toRouter (&EnumValuesRouterPayload_toRouter())[2] {
  static const RouterPayload_toRouter values[] = {
    RouterPayload_toRouter_NONE,
    RouterPayload_toRouter_enableAppRegister
  };
  return values;
}

inline const char * const *EnumNamesRouterPayload_toRouter() {
  static const char * const names[3] = {
    "NONE",
    "enableAppRegister",
    nullptr
  };
  return names;
}

inline const char *EnumNameRouterPayload_toRouter(RouterPayload_toRouter e) {
  if (::flatbuffers::IsOutRange(e, RouterPayload_toRouter_NONE, RouterPayload_toRouter_enableAppRegister)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRouterPayload_toRouter()[index];
}

template<typename T> struct RouterPayload_toRouterTraits {
  static const RouterPayload_toRouter enum_value = RouterPayload_toRouter_NONE;
};

template<> struct RouterPayload_toRouterTraits<SuOS::Uds::Msg::Router::enableAppRegister> {
  static const RouterPayload_toRouter enum_value = RouterPayload_toRouter_enableAppRegister;
};

bool VerifyRouterPayload_toRouter(::flatbuffers::Verifier &verifier, const void *obj, RouterPayload_toRouter type);
bool VerifyRouterPayload_toRouterVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct enableAppRegister FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef enableAppRegisterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_APP_ID = 4
  };
  uint32_t app_id() const {
    return GetField<uint32_t>(VT_APP_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_APP_ID, 4) &&
           verifier.EndTable();
  }
};

struct enableAppRegisterBuilder {
  typedef enableAppRegister Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_app_id(uint32_t app_id) {
    fbb_.AddElement<uint32_t>(enableAppRegister::VT_APP_ID, app_id, 0);
  }
  explicit enableAppRegisterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<enableAppRegister> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<enableAppRegister>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<enableAppRegister> CreateenableAppRegister(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t app_id = 0) {
  enableAppRegisterBuilder builder_(_fbb);
  builder_.add_app_id(app_id);
  return builder_.Finish();
}

struct RouterEnvelope_toRouter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RouterEnvelope_toRouterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::Router::RouterPayload_toRouter payload_type() const {
    return static_cast<SuOS::Uds::Msg::Router::RouterPayload_toRouter>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::Router::enableAppRegister *payload_as_enableAppRegister() const {
    return payload_type() == SuOS::Uds::Msg::Router::RouterPayload_toRouter_enableAppRegister ? static_cast<const SuOS::Uds::Msg::Router::enableAppRegister *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyRouterPayload_toRouter(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::Router::enableAppRegister *RouterEnvelope_toRouter::payload_as<SuOS::Uds::Msg::Router::enableAppRegister>() const {
  return payload_as_enableAppRegister();
}

struct RouterEnvelope_toRouterBuilder {
  typedef RouterEnvelope_toRouter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::Router::RouterPayload_toRouter payload_type) {
    fbb_.AddElement<uint8_t>(RouterEnvelope_toRouter::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RouterEnvelope_toRouter::VT_PAYLOAD, payload);
  }
  explicit RouterEnvelope_toRouterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RouterEnvelope_toRouter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RouterEnvelope_toRouter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RouterEnvelope_toRouter> CreateRouterEnvelope_toRouter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::Router::RouterPayload_toRouter payload_type = SuOS::Uds::Msg::Router::RouterPayload_toRouter_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  RouterEnvelope_toRouterBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyRouterPayload_toRouter(::flatbuffers::Verifier &verifier, const void *obj, RouterPayload_toRouter type) {
  switch (type) {
    case RouterPayload_toRouter_NONE: {
      return true;
    }
    case RouterPayload_toRouter_enableAppRegister: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Router::enableAppRegister *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRouterPayload_toRouterVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRouterPayload_toRouter(
        verifier,  values->Get(i), types->GetEnum<RouterPayload_toRouter>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::Router::RouterEnvelope_toRouter *GetRouterEnvelope_toRouter(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::Router::RouterEnvelope_toRouter>(buf);
}

inline const SuOS::Uds::Msg::Router::RouterEnvelope_toRouter *GetSizePrefixedRouterEnvelope_toRouter(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::Router::RouterEnvelope_toRouter>(buf);
}

inline bool VerifyRouterEnvelope_toRouterBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::Router::RouterEnvelope_toRouter>(nullptr);
}

inline bool VerifySizePrefixedRouterEnvelope_toRouterBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::Router::RouterEnvelope_toRouter>(nullptr);
}

inline void FinishRouterEnvelope_toRouterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Router::RouterEnvelope_toRouter> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRouterEnvelope_toRouterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Router::RouterEnvelope_toRouter> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Router
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_ROUTERMSGTOROUTER_SUOS_UDS_MSG_ROUTER_H_
