// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROUTERMSG_SUOS_UDS_MSG_ROUTER_H_
#define FLATBUFFERS_GENERATED_ROUTERMSG_SUOS_UDS_MSG_ROUTER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace Router {

struct enableAppRegister;
struct enableAppRegisterBuilder;

struct onConnect;
struct onConnectBuilder;

struct onConnectionLost;
struct onConnectionLostBuilder;

struct RouterEnvelope;
struct RouterEnvelopeBuilder;

enum RouterPayload : uint8_t {
  RouterPayload_NONE = 0,
  RouterPayload_enableAppRegister = 1,
  RouterPayload_onConnect = 2,
  RouterPayload_onConnectionLost = 3,
  RouterPayload_MIN = RouterPayload_NONE,
  RouterPayload_MAX = RouterPayload_onConnectionLost
};

inline const RouterPayload (&EnumValuesRouterPayload())[4] {
  static const RouterPayload values[] = {
    RouterPayload_NONE,
    RouterPayload_enableAppRegister,
    RouterPayload_onConnect,
    RouterPayload_onConnectionLost
  };
  return values;
}

inline const char * const *EnumNamesRouterPayload() {
  static const char * const names[5] = {
    "NONE",
    "enableAppRegister",
    "onConnect",
    "onConnectionLost",
    nullptr
  };
  return names;
}

inline const char *EnumNameRouterPayload(RouterPayload e) {
  if (::flatbuffers::IsOutRange(e, RouterPayload_NONE, RouterPayload_onConnectionLost)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRouterPayload()[index];
}

template<typename T> struct RouterPayloadTraits {
  static const RouterPayload enum_value = RouterPayload_NONE;
};

template<> struct RouterPayloadTraits<SuOS::Uds::Msg::Router::enableAppRegister> {
  static const RouterPayload enum_value = RouterPayload_enableAppRegister;
};

template<> struct RouterPayloadTraits<SuOS::Uds::Msg::Router::onConnect> {
  static const RouterPayload enum_value = RouterPayload_onConnect;
};

template<> struct RouterPayloadTraits<SuOS::Uds::Msg::Router::onConnectionLost> {
  static const RouterPayload enum_value = RouterPayload_onConnectionLost;
};

bool VerifyRouterPayload(::flatbuffers::Verifier &verifier, const void *obj, RouterPayload type);
bool VerifyRouterPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct enableAppRegister FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef enableAppRegisterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_APP_ID = 4
  };
  uint32_t app_id() const {
    return GetField<uint32_t>(VT_APP_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_APP_ID, 4) &&
           verifier.EndTable();
  }
};

struct enableAppRegisterBuilder {
  typedef enableAppRegister Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_app_id(uint32_t app_id) {
    fbb_.AddElement<uint32_t>(enableAppRegister::VT_APP_ID, app_id, 0);
  }
  explicit enableAppRegisterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<enableAppRegister> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<enableAppRegister>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<enableAppRegister> CreateenableAppRegister(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t app_id = 0) {
  enableAppRegisterBuilder builder_(_fbb);
  builder_.add_app_id(app_id);
  return builder_.Finish();
}

struct onConnect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef onConnectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct onConnectBuilder {
  typedef onConnect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(onConnect::VT_ID, id, 0);
  }
  explicit onConnectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<onConnect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<onConnect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<onConnect> CreateonConnect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  onConnectBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct onConnectionLost FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef onConnectionLostBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct onConnectionLostBuilder {
  typedef onConnectionLost Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(onConnectionLost::VT_ID, id, 0);
  }
  explicit onConnectionLostBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<onConnectionLost> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<onConnectionLost>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<onConnectionLost> CreateonConnectionLost(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  onConnectionLostBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct RouterEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RouterEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::Router::RouterPayload payload_type() const {
    return static_cast<SuOS::Uds::Msg::Router::RouterPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::Router::enableAppRegister *payload_as_enableAppRegister() const {
    return payload_type() == SuOS::Uds::Msg::Router::RouterPayload_enableAppRegister ? static_cast<const SuOS::Uds::Msg::Router::enableAppRegister *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::Router::onConnect *payload_as_onConnect() const {
    return payload_type() == SuOS::Uds::Msg::Router::RouterPayload_onConnect ? static_cast<const SuOS::Uds::Msg::Router::onConnect *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::Router::onConnectionLost *payload_as_onConnectionLost() const {
    return payload_type() == SuOS::Uds::Msg::Router::RouterPayload_onConnectionLost ? static_cast<const SuOS::Uds::Msg::Router::onConnectionLost *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyRouterPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::Router::enableAppRegister *RouterEnvelope::payload_as<SuOS::Uds::Msg::Router::enableAppRegister>() const {
  return payload_as_enableAppRegister();
}

template<> inline const SuOS::Uds::Msg::Router::onConnect *RouterEnvelope::payload_as<SuOS::Uds::Msg::Router::onConnect>() const {
  return payload_as_onConnect();
}

template<> inline const SuOS::Uds::Msg::Router::onConnectionLost *RouterEnvelope::payload_as<SuOS::Uds::Msg::Router::onConnectionLost>() const {
  return payload_as_onConnectionLost();
}

struct RouterEnvelopeBuilder {
  typedef RouterEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::Router::RouterPayload payload_type) {
    fbb_.AddElement<uint8_t>(RouterEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RouterEnvelope::VT_PAYLOAD, payload);
  }
  explicit RouterEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RouterEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RouterEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RouterEnvelope> CreateRouterEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::Router::RouterPayload payload_type = SuOS::Uds::Msg::Router::RouterPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  RouterEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyRouterPayload(::flatbuffers::Verifier &verifier, const void *obj, RouterPayload type) {
  switch (type) {
    case RouterPayload_NONE: {
      return true;
    }
    case RouterPayload_enableAppRegister: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Router::enableAppRegister *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RouterPayload_onConnect: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Router::onConnect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RouterPayload_onConnectionLost: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Router::onConnectionLost *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRouterPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRouterPayload(
        verifier,  values->Get(i), types->GetEnum<RouterPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::Router::RouterEnvelope *GetRouterEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::Router::RouterEnvelope>(buf);
}

inline const SuOS::Uds::Msg::Router::RouterEnvelope *GetSizePrefixedRouterEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::Router::RouterEnvelope>(buf);
}

inline bool VerifyRouterEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::Router::RouterEnvelope>(nullptr);
}

inline bool VerifySizePrefixedRouterEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::Router::RouterEnvelope>(nullptr);
}

inline void FinishRouterEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Router::RouterEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRouterEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Router::RouterEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Router
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_ROUTERMSG_SUOS_UDS_MSG_ROUTER_H_
