// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ROUTERMSGFROMROUTER_SUOS_UDS_MSG_ROUTER_H_
#define FLATBUFFERS_GENERATED_ROUTERMSGFROMROUTER_SUOS_UDS_MSG_ROUTER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace Router {

struct onConnect;
struct onConnectBuilder;

struct onConnectionLost;
struct onConnectionLostBuilder;

struct RouterEnvelope_fromRouter;
struct RouterEnvelope_fromRouterBuilder;

enum RouterPayload_fromRouter : uint8_t {
  RouterPayload_fromRouter_NONE = 0,
  RouterPayload_fromRouter_onConnect = 1,
  RouterPayload_fromRouter_onConnectionLost = 2,
  RouterPayload_fromRouter_MIN = RouterPayload_fromRouter_NONE,
  RouterPayload_fromRouter_MAX = RouterPayload_fromRouter_onConnectionLost
};

inline const RouterPayload_fromRouter (&EnumValuesRouterPayload_fromRouter())[3] {
  static const RouterPayload_fromRouter values[] = {
    RouterPayload_fromRouter_NONE,
    RouterPayload_fromRouter_onConnect,
    RouterPayload_fromRouter_onConnectionLost
  };
  return values;
}

inline const char * const *EnumNamesRouterPayload_fromRouter() {
  static const char * const names[4] = {
    "NONE",
    "onConnect",
    "onConnectionLost",
    nullptr
  };
  return names;
}

inline const char *EnumNameRouterPayload_fromRouter(RouterPayload_fromRouter e) {
  if (::flatbuffers::IsOutRange(e, RouterPayload_fromRouter_NONE, RouterPayload_fromRouter_onConnectionLost)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRouterPayload_fromRouter()[index];
}

template<typename T> struct RouterPayload_fromRouterTraits {
  static const RouterPayload_fromRouter enum_value = RouterPayload_fromRouter_NONE;
};

template<> struct RouterPayload_fromRouterTraits<SuOS::Uds::Msg::Router::onConnect> {
  static const RouterPayload_fromRouter enum_value = RouterPayload_fromRouter_onConnect;
};

template<> struct RouterPayload_fromRouterTraits<SuOS::Uds::Msg::Router::onConnectionLost> {
  static const RouterPayload_fromRouter enum_value = RouterPayload_fromRouter_onConnectionLost;
};

bool VerifyRouterPayload_fromRouter(::flatbuffers::Verifier &verifier, const void *obj, RouterPayload_fromRouter type);
bool VerifyRouterPayload_fromRouterVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct onConnect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef onConnectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct onConnectBuilder {
  typedef onConnect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(onConnect::VT_ID, id, 0);
  }
  explicit onConnectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<onConnect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<onConnect>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<onConnect> CreateonConnect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  onConnectBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct onConnectionLost FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef onConnectionLostBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct onConnectionLostBuilder {
  typedef onConnectionLost Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(onConnectionLost::VT_ID, id, 0);
  }
  explicit onConnectionLostBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<onConnectionLost> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<onConnectionLost>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<onConnectionLost> CreateonConnectionLost(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  onConnectionLostBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct RouterEnvelope_fromRouter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RouterEnvelope_fromRouterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::Router::RouterPayload_fromRouter payload_type() const {
    return static_cast<SuOS::Uds::Msg::Router::RouterPayload_fromRouter>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::Router::onConnect *payload_as_onConnect() const {
    return payload_type() == SuOS::Uds::Msg::Router::RouterPayload_fromRouter_onConnect ? static_cast<const SuOS::Uds::Msg::Router::onConnect *>(payload()) : nullptr;
  }
  const SuOS::Uds::Msg::Router::onConnectionLost *payload_as_onConnectionLost() const {
    return payload_type() == SuOS::Uds::Msg::Router::RouterPayload_fromRouter_onConnectionLost ? static_cast<const SuOS::Uds::Msg::Router::onConnectionLost *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyRouterPayload_fromRouter(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::Router::onConnect *RouterEnvelope_fromRouter::payload_as<SuOS::Uds::Msg::Router::onConnect>() const {
  return payload_as_onConnect();
}

template<> inline const SuOS::Uds::Msg::Router::onConnectionLost *RouterEnvelope_fromRouter::payload_as<SuOS::Uds::Msg::Router::onConnectionLost>() const {
  return payload_as_onConnectionLost();
}

struct RouterEnvelope_fromRouterBuilder {
  typedef RouterEnvelope_fromRouter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::Router::RouterPayload_fromRouter payload_type) {
    fbb_.AddElement<uint8_t>(RouterEnvelope_fromRouter::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RouterEnvelope_fromRouter::VT_PAYLOAD, payload);
  }
  explicit RouterEnvelope_fromRouterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RouterEnvelope_fromRouter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RouterEnvelope_fromRouter>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RouterEnvelope_fromRouter> CreateRouterEnvelope_fromRouter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::Router::RouterPayload_fromRouter payload_type = SuOS::Uds::Msg::Router::RouterPayload_fromRouter_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  RouterEnvelope_fromRouterBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyRouterPayload_fromRouter(::flatbuffers::Verifier &verifier, const void *obj, RouterPayload_fromRouter type) {
  switch (type) {
    case RouterPayload_fromRouter_NONE: {
      return true;
    }
    case RouterPayload_fromRouter_onConnect: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Router::onConnect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case RouterPayload_fromRouter_onConnectionLost: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Router::onConnectionLost *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRouterPayload_fromRouterVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRouterPayload_fromRouter(
        verifier,  values->Get(i), types->GetEnum<RouterPayload_fromRouter>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter *GetRouterEnvelope_fromRouter(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter>(buf);
}

inline const SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter *GetSizePrefixedRouterEnvelope_fromRouter(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter>(buf);
}

inline bool VerifyRouterEnvelope_fromRouterBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter>(nullptr);
}

inline bool VerifySizePrefixedRouterEnvelope_fromRouterBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter>(nullptr);
}

inline void FinishRouterEnvelope_fromRouterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRouterEnvelope_fromRouterBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Router::RouterEnvelope_fromRouter> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Router
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_ROUTERMSGFROMROUTER_SUOS_UDS_MSG_ROUTER_H_
