// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAPHICSMSGFROMRGA_SUOS_UDS_MSG_GRAPHICS_H_
#define FLATBUFFERS_GENERATED_GRAPHICSMSGFROMRGA_SUOS_UDS_MSG_GRAPHICS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace Graphics {

struct RgaResponse;
struct RgaResponseBuilder;

struct FromRgaEnvelope;
struct FromRgaEnvelopeBuilder;

enum FromRgaPayload : uint8_t {
  FromRgaPayload_NONE = 0,
  FromRgaPayload_RgaResponse = 1,
  FromRgaPayload_MIN = FromRgaPayload_NONE,
  FromRgaPayload_MAX = FromRgaPayload_RgaResponse
};

inline const FromRgaPayload (&EnumValuesFromRgaPayload())[2] {
  static const FromRgaPayload values[] = {
    FromRgaPayload_NONE,
    FromRgaPayload_RgaResponse
  };
  return values;
}

inline const char * const *EnumNamesFromRgaPayload() {
  static const char * const names[3] = {
    "NONE",
    "RgaResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameFromRgaPayload(FromRgaPayload e) {
  if (::flatbuffers::IsOutRange(e, FromRgaPayload_NONE, FromRgaPayload_RgaResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFromRgaPayload()[index];
}

template<typename T> struct FromRgaPayloadTraits {
  static const FromRgaPayload enum_value = FromRgaPayload_NONE;
};

template<> struct FromRgaPayloadTraits<SuOS::Uds::Msg::Graphics::RgaResponse> {
  static const FromRgaPayload enum_value = FromRgaPayload_RgaResponse;
};

bool VerifyFromRgaPayload(::flatbuffers::Verifier &verifier, const void *obj, FromRgaPayload type);
bool VerifyFromRgaPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct RgaResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RgaResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_JOB_ID = 4,
    VT_ERR_CODE = 6
  };
  uint32_t job_id() const {
    return GetField<uint32_t>(VT_JOB_ID, 0);
  }
  uint32_t err_code() const {
    return GetField<uint32_t>(VT_ERR_CODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_JOB_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ERR_CODE, 4) &&
           verifier.EndTable();
  }
};

struct RgaResponseBuilder {
  typedef RgaResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_job_id(uint32_t job_id) {
    fbb_.AddElement<uint32_t>(RgaResponse::VT_JOB_ID, job_id, 0);
  }
  void add_err_code(uint32_t err_code) {
    fbb_.AddElement<uint32_t>(RgaResponse::VT_ERR_CODE, err_code, 0);
  }
  explicit RgaResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RgaResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RgaResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RgaResponse> CreateRgaResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t job_id = 0,
    uint32_t err_code = 0) {
  RgaResponseBuilder builder_(_fbb);
  builder_.add_err_code(err_code);
  builder_.add_job_id(job_id);
  return builder_.Finish();
}

struct FromRgaEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FromRgaEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::Graphics::FromRgaPayload payload_type() const {
    return static_cast<SuOS::Uds::Msg::Graphics::FromRgaPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::Graphics::RgaResponse *payload_as_RgaResponse() const {
    return payload_type() == SuOS::Uds::Msg::Graphics::FromRgaPayload_RgaResponse ? static_cast<const SuOS::Uds::Msg::Graphics::RgaResponse *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyFromRgaPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::Graphics::RgaResponse *FromRgaEnvelope::payload_as<SuOS::Uds::Msg::Graphics::RgaResponse>() const {
  return payload_as_RgaResponse();
}

struct FromRgaEnvelopeBuilder {
  typedef FromRgaEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::Graphics::FromRgaPayload payload_type) {
    fbb_.AddElement<uint8_t>(FromRgaEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(FromRgaEnvelope::VT_PAYLOAD, payload);
  }
  explicit FromRgaEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FromRgaEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FromRgaEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FromRgaEnvelope> CreateFromRgaEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::Graphics::FromRgaPayload payload_type = SuOS::Uds::Msg::Graphics::FromRgaPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  FromRgaEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyFromRgaPayload(::flatbuffers::Verifier &verifier, const void *obj, FromRgaPayload type) {
  switch (type) {
    case FromRgaPayload_NONE: {
      return true;
    }
    case FromRgaPayload_RgaResponse: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Graphics::RgaResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyFromRgaPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyFromRgaPayload(
        verifier,  values->Get(i), types->GetEnum<FromRgaPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::Graphics::FromRgaEnvelope *GetFromRgaEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::Graphics::FromRgaEnvelope>(buf);
}

inline const SuOS::Uds::Msg::Graphics::FromRgaEnvelope *GetSizePrefixedFromRgaEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::Graphics::FromRgaEnvelope>(buf);
}

inline bool VerifyFromRgaEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::Graphics::FromRgaEnvelope>(nullptr);
}

inline bool VerifySizePrefixedFromRgaEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::Graphics::FromRgaEnvelope>(nullptr);
}

inline void FinishFromRgaEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Graphics::FromRgaEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFromRgaEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Graphics::FromRgaEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Graphics
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_GRAPHICSMSGFROMRGA_SUOS_UDS_MSG_GRAPHICS_H_
