// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRAPHICSMSGTORGA_SUOS_UDS_MSG_GRAPHICS_H_
#define FLATBUFFERS_GENERATED_GRAPHICSMSGTORGA_SUOS_UDS_MSG_GRAPHICS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace SuOS {
namespace Uds {
namespace Msg {
namespace Graphics {

struct RgaRequest;
struct RgaRequestBuilder;

struct ToRgaEnvelope;
struct ToRgaEnvelopeBuilder;

enum RgaStepType : int8_t {
  RgaStepType_COPY = 0,
  RgaStepType_ROTATE = 1,
  RgaStepType_FILL = 2,
  RgaStepType_BLEND = 3,
  RgaStepType_OSD = 4,
  RgaStepType_RESIZE = 5,
  RgaStepType_CROP = 6,
  RgaStepType_COLOR_CONVERT = 7,
  RgaStepType_FLIP = 8,
  RgaStepType_COMPOSITE = 9,
  RgaStepType_COLOR_KEY = 10,
  RgaStepType_MOSAIC = 11,
  RgaStepType_RECTANGLE = 12,
  RgaStepType_MIN = RgaStepType_COPY,
  RgaStepType_MAX = RgaStepType_RECTANGLE
};

inline const RgaStepType (&EnumValuesRgaStepType())[13] {
  static const RgaStepType values[] = {
    RgaStepType_COPY,
    RgaStepType_ROTATE,
    RgaStepType_FILL,
    RgaStepType_BLEND,
    RgaStepType_OSD,
    RgaStepType_RESIZE,
    RgaStepType_CROP,
    RgaStepType_COLOR_CONVERT,
    RgaStepType_FLIP,
    RgaStepType_COMPOSITE,
    RgaStepType_COLOR_KEY,
    RgaStepType_MOSAIC,
    RgaStepType_RECTANGLE
  };
  return values;
}

inline const char * const *EnumNamesRgaStepType() {
  static const char * const names[14] = {
    "COPY",
    "ROTATE",
    "FILL",
    "BLEND",
    "OSD",
    "RESIZE",
    "CROP",
    "COLOR_CONVERT",
    "FLIP",
    "COMPOSITE",
    "COLOR_KEY",
    "MOSAIC",
    "RECTANGLE",
    nullptr
  };
  return names;
}

inline const char *EnumNameRgaStepType(RgaStepType e) {
  if (::flatbuffers::IsOutRange(e, RgaStepType_COPY, RgaStepType_RECTANGLE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRgaStepType()[index];
}

enum ToRgaPayload : uint8_t {
  ToRgaPayload_NONE = 0,
  ToRgaPayload_RgaRequest = 1,
  ToRgaPayload_MIN = ToRgaPayload_NONE,
  ToRgaPayload_MAX = ToRgaPayload_RgaRequest
};

inline const ToRgaPayload (&EnumValuesToRgaPayload())[2] {
  static const ToRgaPayload values[] = {
    ToRgaPayload_NONE,
    ToRgaPayload_RgaRequest
  };
  return values;
}

inline const char * const *EnumNamesToRgaPayload() {
  static const char * const names[3] = {
    "NONE",
    "RgaRequest",
    nullptr
  };
  return names;
}

inline const char *EnumNameToRgaPayload(ToRgaPayload e) {
  if (::flatbuffers::IsOutRange(e, ToRgaPayload_NONE, ToRgaPayload_RgaRequest)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesToRgaPayload()[index];
}

template<typename T> struct ToRgaPayloadTraits {
  static const ToRgaPayload enum_value = ToRgaPayload_NONE;
};

template<> struct ToRgaPayloadTraits<SuOS::Uds::Msg::Graphics::RgaRequest> {
  static const ToRgaPayload enum_value = ToRgaPayload_RgaRequest;
};

bool VerifyToRgaPayload(::flatbuffers::Verifier &verifier, const void *obj, ToRgaPayload type);
bool VerifyToRgaPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct RgaRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RgaRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_JOB_ID = 4,
    VT_TYPE = 6,
    VT_SRC_FD = 8,
    VT_SRC_W = 10,
    VT_SRC_H = 12,
    VT_SRC_FMT = 14,
    VT_SRC_X = 16,
    VT_SRC_Y = 18,
    VT_DST_FD = 20,
    VT_DST_W = 22,
    VT_DST_H = 24,
    VT_DST_FMT = 26,
    VT_DST_X = 28,
    VT_DST_Y = 30,
    VT_PAT_FD = 32,
    VT_PAT_W = 34,
    VT_PAT_H = 36,
    VT_PAT_FMT = 38,
    VT_PAT_X = 40,
    VT_PAT_Y = 42,
    VT_ANGLE = 44,
    VT_COLOR = 46,
    VT_MODE = 48,
    VT_FX = 50,
    VT_FY = 52
  };
  uint32_t job_id() const {
    return GetField<uint32_t>(VT_JOB_ID, 0);
  }
  int8_t type() const {
    return GetField<int8_t>(VT_TYPE, 0);
  }
  int32_t src_fd() const {
    return GetField<int32_t>(VT_SRC_FD, 0);
  }
  int32_t src_w() const {
    return GetField<int32_t>(VT_SRC_W, 0);
  }
  int32_t src_h() const {
    return GetField<int32_t>(VT_SRC_H, 0);
  }
  int32_t src_fmt() const {
    return GetField<int32_t>(VT_SRC_FMT, 0);
  }
  int32_t src_x() const {
    return GetField<int32_t>(VT_SRC_X, 0);
  }
  int32_t src_y() const {
    return GetField<int32_t>(VT_SRC_Y, 0);
  }
  int32_t dst_fd() const {
    return GetField<int32_t>(VT_DST_FD, 0);
  }
  int32_t dst_w() const {
    return GetField<int32_t>(VT_DST_W, 0);
  }
  int32_t dst_h() const {
    return GetField<int32_t>(VT_DST_H, 0);
  }
  int32_t dst_fmt() const {
    return GetField<int32_t>(VT_DST_FMT, 0);
  }
  int32_t dst_x() const {
    return GetField<int32_t>(VT_DST_X, 0);
  }
  int32_t dst_y() const {
    return GetField<int32_t>(VT_DST_Y, 0);
  }
  int32_t pat_fd() const {
    return GetField<int32_t>(VT_PAT_FD, 0);
  }
  int32_t pat_w() const {
    return GetField<int32_t>(VT_PAT_W, 0);
  }
  int32_t pat_h() const {
    return GetField<int32_t>(VT_PAT_H, 0);
  }
  int32_t pat_fmt() const {
    return GetField<int32_t>(VT_PAT_FMT, 0);
  }
  int32_t pat_x() const {
    return GetField<int32_t>(VT_PAT_X, 0);
  }
  int32_t pat_y() const {
    return GetField<int32_t>(VT_PAT_Y, 0);
  }
  int32_t angle() const {
    return GetField<int32_t>(VT_ANGLE, 0);
  }
  uint32_t color() const {
    return GetField<uint32_t>(VT_COLOR, 0);
  }
  int32_t mode() const {
    return GetField<int32_t>(VT_MODE, 0);
  }
  double fx() const {
    return GetField<double>(VT_FX, 0.0);
  }
  double fy() const {
    return GetField<double>(VT_FY, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_JOB_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int32_t>(verifier, VT_SRC_FD, 4) &&
           VerifyField<int32_t>(verifier, VT_SRC_W, 4) &&
           VerifyField<int32_t>(verifier, VT_SRC_H, 4) &&
           VerifyField<int32_t>(verifier, VT_SRC_FMT, 4) &&
           VerifyField<int32_t>(verifier, VT_SRC_X, 4) &&
           VerifyField<int32_t>(verifier, VT_SRC_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_DST_FD, 4) &&
           VerifyField<int32_t>(verifier, VT_DST_W, 4) &&
           VerifyField<int32_t>(verifier, VT_DST_H, 4) &&
           VerifyField<int32_t>(verifier, VT_DST_FMT, 4) &&
           VerifyField<int32_t>(verifier, VT_DST_X, 4) &&
           VerifyField<int32_t>(verifier, VT_DST_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_PAT_FD, 4) &&
           VerifyField<int32_t>(verifier, VT_PAT_W, 4) &&
           VerifyField<int32_t>(verifier, VT_PAT_H, 4) &&
           VerifyField<int32_t>(verifier, VT_PAT_FMT, 4) &&
           VerifyField<int32_t>(verifier, VT_PAT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_PAT_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_ANGLE, 4) &&
           VerifyField<uint32_t>(verifier, VT_COLOR, 4) &&
           VerifyField<int32_t>(verifier, VT_MODE, 4) &&
           VerifyField<double>(verifier, VT_FX, 8) &&
           VerifyField<double>(verifier, VT_FY, 8) &&
           verifier.EndTable();
  }
};

struct RgaRequestBuilder {
  typedef RgaRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_job_id(uint32_t job_id) {
    fbb_.AddElement<uint32_t>(RgaRequest::VT_JOB_ID, job_id, 0);
  }
  void add_type(int8_t type) {
    fbb_.AddElement<int8_t>(RgaRequest::VT_TYPE, type, 0);
  }
  void add_src_fd(int32_t src_fd) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_SRC_FD, src_fd, 0);
  }
  void add_src_w(int32_t src_w) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_SRC_W, src_w, 0);
  }
  void add_src_h(int32_t src_h) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_SRC_H, src_h, 0);
  }
  void add_src_fmt(int32_t src_fmt) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_SRC_FMT, src_fmt, 0);
  }
  void add_src_x(int32_t src_x) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_SRC_X, src_x, 0);
  }
  void add_src_y(int32_t src_y) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_SRC_Y, src_y, 0);
  }
  void add_dst_fd(int32_t dst_fd) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_DST_FD, dst_fd, 0);
  }
  void add_dst_w(int32_t dst_w) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_DST_W, dst_w, 0);
  }
  void add_dst_h(int32_t dst_h) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_DST_H, dst_h, 0);
  }
  void add_dst_fmt(int32_t dst_fmt) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_DST_FMT, dst_fmt, 0);
  }
  void add_dst_x(int32_t dst_x) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_DST_X, dst_x, 0);
  }
  void add_dst_y(int32_t dst_y) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_DST_Y, dst_y, 0);
  }
  void add_pat_fd(int32_t pat_fd) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_PAT_FD, pat_fd, 0);
  }
  void add_pat_w(int32_t pat_w) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_PAT_W, pat_w, 0);
  }
  void add_pat_h(int32_t pat_h) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_PAT_H, pat_h, 0);
  }
  void add_pat_fmt(int32_t pat_fmt) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_PAT_FMT, pat_fmt, 0);
  }
  void add_pat_x(int32_t pat_x) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_PAT_X, pat_x, 0);
  }
  void add_pat_y(int32_t pat_y) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_PAT_Y, pat_y, 0);
  }
  void add_angle(int32_t angle) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_ANGLE, angle, 0);
  }
  void add_color(uint32_t color) {
    fbb_.AddElement<uint32_t>(RgaRequest::VT_COLOR, color, 0);
  }
  void add_mode(int32_t mode) {
    fbb_.AddElement<int32_t>(RgaRequest::VT_MODE, mode, 0);
  }
  void add_fx(double fx) {
    fbb_.AddElement<double>(RgaRequest::VT_FX, fx, 0.0);
  }
  void add_fy(double fy) {
    fbb_.AddElement<double>(RgaRequest::VT_FY, fy, 0.0);
  }
  explicit RgaRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RgaRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RgaRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RgaRequest> CreateRgaRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t job_id = 0,
    int8_t type = 0,
    int32_t src_fd = 0,
    int32_t src_w = 0,
    int32_t src_h = 0,
    int32_t src_fmt = 0,
    int32_t src_x = 0,
    int32_t src_y = 0,
    int32_t dst_fd = 0,
    int32_t dst_w = 0,
    int32_t dst_h = 0,
    int32_t dst_fmt = 0,
    int32_t dst_x = 0,
    int32_t dst_y = 0,
    int32_t pat_fd = 0,
    int32_t pat_w = 0,
    int32_t pat_h = 0,
    int32_t pat_fmt = 0,
    int32_t pat_x = 0,
    int32_t pat_y = 0,
    int32_t angle = 0,
    uint32_t color = 0,
    int32_t mode = 0,
    double fx = 0.0,
    double fy = 0.0) {
  RgaRequestBuilder builder_(_fbb);
  builder_.add_fy(fy);
  builder_.add_fx(fx);
  builder_.add_mode(mode);
  builder_.add_color(color);
  builder_.add_angle(angle);
  builder_.add_pat_y(pat_y);
  builder_.add_pat_x(pat_x);
  builder_.add_pat_fmt(pat_fmt);
  builder_.add_pat_h(pat_h);
  builder_.add_pat_w(pat_w);
  builder_.add_pat_fd(pat_fd);
  builder_.add_dst_y(dst_y);
  builder_.add_dst_x(dst_x);
  builder_.add_dst_fmt(dst_fmt);
  builder_.add_dst_h(dst_h);
  builder_.add_dst_w(dst_w);
  builder_.add_dst_fd(dst_fd);
  builder_.add_src_y(src_y);
  builder_.add_src_x(src_x);
  builder_.add_src_fmt(src_fmt);
  builder_.add_src_h(src_h);
  builder_.add_src_w(src_w);
  builder_.add_src_fd(src_fd);
  builder_.add_job_id(job_id);
  builder_.add_type(type);
  return builder_.Finish();
}

struct ToRgaEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ToRgaEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  SuOS::Uds::Msg::Graphics::ToRgaPayload payload_type() const {
    return static_cast<SuOS::Uds::Msg::Graphics::ToRgaPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const SuOS::Uds::Msg::Graphics::RgaRequest *payload_as_RgaRequest() const {
    return payload_type() == SuOS::Uds::Msg::Graphics::ToRgaPayload_RgaRequest ? static_cast<const SuOS::Uds::Msg::Graphics::RgaRequest *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyToRgaPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const SuOS::Uds::Msg::Graphics::RgaRequest *ToRgaEnvelope::payload_as<SuOS::Uds::Msg::Graphics::RgaRequest>() const {
  return payload_as_RgaRequest();
}

struct ToRgaEnvelopeBuilder {
  typedef ToRgaEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(SuOS::Uds::Msg::Graphics::ToRgaPayload payload_type) {
    fbb_.AddElement<uint8_t>(ToRgaEnvelope::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(ToRgaEnvelope::VT_PAYLOAD, payload);
  }
  explicit ToRgaEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ToRgaEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ToRgaEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ToRgaEnvelope> CreateToRgaEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SuOS::Uds::Msg::Graphics::ToRgaPayload payload_type = SuOS::Uds::Msg::Graphics::ToRgaPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  ToRgaEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyToRgaPayload(::flatbuffers::Verifier &verifier, const void *obj, ToRgaPayload type) {
  switch (type) {
    case ToRgaPayload_NONE: {
      return true;
    }
    case ToRgaPayload_RgaRequest: {
      auto ptr = reinterpret_cast<const SuOS::Uds::Msg::Graphics::RgaRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyToRgaPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyToRgaPayload(
        verifier,  values->Get(i), types->GetEnum<ToRgaPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const SuOS::Uds::Msg::Graphics::ToRgaEnvelope *GetToRgaEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<SuOS::Uds::Msg::Graphics::ToRgaEnvelope>(buf);
}

inline const SuOS::Uds::Msg::Graphics::ToRgaEnvelope *GetSizePrefixedToRgaEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SuOS::Uds::Msg::Graphics::ToRgaEnvelope>(buf);
}

inline bool VerifyToRgaEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SuOS::Uds::Msg::Graphics::ToRgaEnvelope>(nullptr);
}

inline bool VerifySizePrefixedToRgaEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SuOS::Uds::Msg::Graphics::ToRgaEnvelope>(nullptr);
}

inline void FinishToRgaEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Graphics::ToRgaEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedToRgaEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SuOS::Uds::Msg::Graphics::ToRgaEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Graphics
}  // namespace Msg
}  // namespace Uds
}  // namespace SuOS

#endif  // FLATBUFFERS_GENERATED_GRAPHICSMSGTORGA_SUOS_UDS_MSG_GRAPHICS_H_
